### ISSUE TITLE
Question: Error on Mac by evaluating the gui

### ISSUE THREAD

**Issue by Xon77** [thgrund/SuperDirtMixer#2]
After booting SuperDirtMixer like in the helpfile, when I try to evaluate `~mixer.gui`, I've got the following error.
I have for sure missed something in the installation, but I do not know what?
I am on Mac with SC 3.13
Thanks

SuperDirtMixer was successfully initialized
ERROR: Message 'synth' not understood.
Perhaps you misspelled 'switch', or meant to call 'synth' on another receiver?
RECEIVER:
Instance of GlobalDirtEffect {    (0x1701f1e58, gc=A0, fmt=00, flg=00, set=03)
  instance variables [7]
    name : Symbol 'dirt_global_eq'
    paramNames : instance of Array (0x150593698, size=1, set=2)
    numChannels : Integer 2
    state : instance of Event (0x1604b4f68, size=5, set=3)
    alwaysRun : false
    synth : instance of Synth (0x175995508, size=6, set=3)
    defName : nil
}
ARGS:
PATH: /Users/xon/Live4Life/L4L_Project/_0A_Init_Live4Life.scd
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = <instance of GlobalDirtEffect>
		arg selector = 'synth'
		arg args = [*0]
	SuperDirtMixer:gui
		arg this = <instance of SuperDirtMixer>
		var window = nil
		var v = nil
		var composite = <instance of CompositeView>
		var freqScope = <instance of FreqScopeView>
		var orbitUIElements = nil
		var masterFunc = nil
		var meterResp = nil
		var masterOutResp = nil
		var loadPresetListener = nil
		var equiView = nil
		var setEQuiValues = nil
		var activeOrbit = <instance of DirtOrbit>
		var presetFile = 'Default.json'
		var orbitLevelIndicators = [*0]
		var panKnobs = [*0]
		var panNumBoxs = [*0]
		var gainSliders = [*0]
		var gainNumBoxs = [*0]
		var reverbKnobs = [*0]
		var eqButtons = <instance of List>
		var orbitMixerViews = [*0]
		var setOrbitEQValues = nil
		var leftMasterIndicator = <instance of LevelIndicator>
		var rightMasterIndicator = <instance of LevelIndicator>
		var panListener = nil
		var gainListener = nil
		var reverbListener = nil
		var presetListView = <instance of ListView>
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "(
    // When you added your..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ ERROR: Message 'synth' not understood.
Perhaps you misspelled 'switch', or meant to call 'synth' on another receiver?
RECEIVER: GlobalDirtEffect('dirt_global_eq', [ 'activeEq' ])

**Comment by thgrund** [comment]
Hey @Xon77! 

This is a well known issue and can be solved by updating SuperDirt. Maybe you need to use the developer branch for it?!
So this version should definitely work and solve your issue: https://github.com/musikinformatik/SuperDirt/archive/refs/heads/develop.zip 

And can be found here: https://github.com/musikinformatik/SuperDirt

**Comment by Xon77** [comment]
Thank you so much! Works great.
